version: 2.0

jobs:
  bundle_dependencies:
    working_directory: ~/drive_info
    docker:
      - image: ruby:2.4.2
    steps:
      - checkout
      - attach_workspace:
          at: ~/drive_info
      - type: cache-restore
        key: drive_info-{{ checksum "Gemfile.lock" }}
      - run: bundle check --path vendor/bundle || bundle install --path vendor/bundle
      - type: cache-save
        key: drive_info-{{ checksum "Gemfile.lock" }}
        paths:
          - ~/drive_info/vendor/bundle
      - persist_to_workspace:
          root: .
          paths:
            - vendor/bundle

  test:
    parallelism: 1
    working_directory: ~/drive_info
    docker:
      - image: ruby:2.4.2
        environment:
          - RAILS_ENV=test
          - RACK_ENV=test
    steps:
      - checkout
      - attach_workspace:
          at: ~/drive_info
      - run: bundle --path vendor/bundle
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            --no-color
      - type: store_test_results
        path: /tmp/test-results

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - bundle_dependencies
      - test:
          requires:
            - bundle_dependencies
